/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    '/3d/tunneltest7_cam_action-transformed.glb',
  );
  const { actions } = useAnimations(animations, group);

  React.useEffect(
    () => void (actions['Action'].play().paused = false),
    [actions],
  );

  React.useEffect(() => console.log('actions', actions), [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Camera"
        position={[0, 0, 28.03]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <PerspectiveCamera
          makeDefault={true}
          far={100}
          near={0.1}
          fov={22.9}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 11.69, 1]}
      />
    </group>
  );
}

useGLTF.preload('/3d/tunneltest7_cam_action-transformed.glb');
